apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  AWS_DEFAULT_REGION: {{ .Values.secret.region | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secret.id | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secret.key | b64enc | quote }}
