annotations:
  artifacthub.io/changes: |
    - Remove serviceName for triton.
  artifacthub.io/images: |
    - name: manager
      image: dragonflyoss/manager:v2.1.43
    - name: scheduler
      image: dragonflyoss/scheduler:v2.1.43
    - name: client
      image: dragonflyoss/client:v0.1.45
    - name: seed-client
      image: dragonflyoss/client:v0.1.45
    - name: dfinit
      image: dragonflyoss/dfinit:v0.1.45
    - name: dfdaemon
      image: dragonflyoss/dfdaemon:v2.1.43
    - name: trainer
      image: dragonflyoss/scheduler:v2.1.43
    - name: triton
      image: nvcr.io/nvidia/tritonserver:23.06-py3
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/dragonflyoss/helm-charts
    - name: Source
      url: https://github.com/dragonflyoss/Dragonfly2
apiVersion: v2
appVersion: 2.1.43
dependencies:
- condition: mysql.enable
  name: mysql
  repository: https://charts.bitnami.com/bitnami
  version: 9.4.6
- condition: redis.enable
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 17.4.3
- condition: jaeger.enable
  name: jaeger
  repository: https://jaegertracing.github.io/helm-charts
  version: 0.66.1
description: Dragonfly is an intelligent P2P based image and file distribution system
home: https://d7y.io/
icon: https://raw.githubusercontent.com/dragonflyoss/Dragonfly2/main/docs/images/logo/dragonfly.svg
keywords:
- dragonfly
- d7y
- P2P
- image
maintainers:
- email: majinjing3@gmail.com
  name: jim3ma
- email: gaius.qi@gmail.com
  name: gaius-qi
- email: aiopsclub@163.com
  name: yxxhero
name: dragonfly
sources:
- https://github.com/dragonflyoss/Dragonfly2
type: application
version: 1.1.55
