replicaCount: 1

image:
  imageName: nvcr.io/nvidia/tritonserver:24.04-py3
  pullPolicy: IfNotPresent
  modelRepositoryPath: s3://triton-inference-server-repository/model_repository
  numGpus: 1

service:
  type: LoadBalancer

secret:
  region: AWS_REGION
  id: AWS_SECRET_KEY_ID
  key: AWS_SECRET_ACCESS_KEY