annotations:
  app.kubesphere.io/category: Storage
apiVersion: v1
appVersion: RELEASE.2020-08-08T04-50-06Z
description: High Performance, Kubernetes Native Object Storage
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
keywords:
- storage
- object-storage
- S3
maintainers:
- email: dev@minio.io
  name: Minio
name: minio
sources:
- https://github.com/minio/minio
version: 6.0.5
